// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiqMztYg4Uydqt8kJATqE2BO7D_lxhHvY',
    appId: '1:905187233490:web:525e68e3a3fa04e096e70b',
    messagingSenderId: '905187233490',
    projectId: 'alkaram-hoseiry',
    authDomain: 'alkaram-hoseiry.firebaseapp.com',
    storageBucket: 'alkaram-hoseiry.firebasestorage.app',
    measurementId: 'G-NG5FBSKLQH',
    databaseURL: 'https://alkaram-hoseiry-default-rtdb.firebaseio.com/'
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOrgkRbOGF-msfeVQsIdQXiqt54oWu68A',
    appId: '1:905187233490:android:c045ef58dc142c0a96e70b',
    messagingSenderId: '905187233490',
    projectId: 'alkaram-hoseiry',
    storageBucket: 'alkaram-hoseiry.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhzM1uRDsbh0h54EPTgCjbyPWLMMGpp9A',
    appId: '1:905187233490:ios:fbc5334f481fb54296e70b',
    messagingSenderId: '905187233490',
    projectId: 'alkaram-hoseiry',
    storageBucket: 'alkaram-hoseiry.firebasestorage.app',
    iosBundleId: 'com.example.alkaramHosiery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhzM1uRDsbh0h54EPTgCjbyPWLMMGpp9A',
    appId: '1:905187233490:ios:fbc5334f481fb54296e70b',
    messagingSenderId: '905187233490',
    projectId: 'alkaram-hoseiry',
    storageBucket: 'alkaram-hoseiry.firebasestorage.app',
    iosBundleId: 'com.example.alkaramHosiery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiqMztYg4Uydqt8kJATqE2BO7D_lxhHvY',
    appId: '1:905187233490:web:b9c98e4f75b5394996e70b',
    messagingSenderId: '905187233490',
    projectId: 'alkaram-hoseiry',
    authDomain: 'alkaram-hoseiry.firebaseapp.com',
    storageBucket: 'alkaram-hoseiry.firebasestorage.app',
    measurementId: 'G-TM2X84NT22',
  );

}